[package]
name = "hyper-openssl"
version = "0.2.8"
authors = ["Steven Fackler <sfackler@gmail.com>"]
description = "Hyper SSL support via OpenSSL"
license = "MIT/Apache-2.0"
repository = "https://github.com/sfackler/hyper-openssl"
documentation = "https://docs.rs/hyper-openssl/0.2.7/hyper_openssl"
readme = "README.md"
exclude = ["test/*"]

[dependencies]
antidote = "1.0"
hyper = "0.10"
openssl = "0.10"
